

CREATE OR REPLACE PROCEDURE CITIRE_CSV IS
	F UTL_FILE.FILE_TYPE;
	V_LINE VARCHAR2(1000);
	V_ID_USER INTEGER;
	V_USERNAME VARCHAR2(30);
	V_PASSWORD VARCHAR2(30);
	V_NUME VARCHAR2(30);
	V_PRENUME VARCHAR2(20);
	V_EMAIL VARCHAR2(30);
	V_SEX VARCHAR2(30);
	V_ORAS VARCHAR2(30);
	V_ADRESA VARCHAR2(50);
	V_TELEFON VARCHAR2(10);
	
BEGIN
	F:=UTL_FILE.FOPEN('DIR5','export_useri.csv','R');
	IF UTL_FILE.IS_OPEN(F) THEN
		LOOP
			BEGIN
				UTL_FILE.GET_LINE(F,V_LINE,1000);
				IF V_LINE IS NULL THEN
					EXIT;
				END IF;
				V_ID_USER:=REGEXP_SUBSTR(V_LINE,'[^;]',1,1);
				V_USERNAME:=REGEXP_SUBSTR(V_LINE,'[^;]',1,2);
				V_PASSWORD:=REGEXP_SUBSTR(V_LINE,'[^;]',1,3);
				V_NUME:=REGEXP_SUBSTR(V_LINE,'[^;]',1,4);
				V_PRENUME:=REGEXP_SUBSTR(V_LINE,'[^;]',1,5);
				V_EMAIL:=REGEXP_SUBSTR(V_LINE,'[^;]',1,6);
				V_SEX:=REGEXP_SUBSTR(V_LINE,'[^;]',1,7);
				V_ORAS:=REGEXP_SUBSTR(V_LINE,'[^;]',1,8);
				V_ADRESA:=REGEXP_SUBSTR(V_LINE,'[^;]',1,9);
				V_TELEFON:=REGEXP_SUBSTR(V_LINE,'[^;]',1,10);
				INSERT INTO USERi10 VALUES(V_ID_USER,V_USERNAME,V_PASSWORD,V_NUME,V_PRENUME,V_EMAIL,V_SEX,V_ORAS,V_ADRESA,V_TELEFON);
				COMMIT;
			EXCEPTION
				WHEN NO_DATA_FOUND THEN
					EXIT;
			END;
		END LOOP;
	END IF;
	UTL_FILE.FCLOSE(F);
END CITIRE_CSV;
/
DECLARE
BEGIN
	CITIRE_CSV;
END;
/