DROP TABLE PARFUM CASCADE CONSTRAINTS;

CREATE TABLE PARFUM(
  id_parfum NUMBER PRIMARY KEY,
  nume_parfum VARCHAR2(40),
  pret NUMBER,
  stoc NUMBER,
  sex VARCHAR2(20),
  id_brand NUMBER,
  gramaj NUMBER,
  categorie VARCHAR2(20),
  concentratie VARCHAR2(20),
  ocazie VARCHAR2(20),
  anotimp VARCHAR2(20),
  poza VARCHAR2(50),
  ingrediente VARCHAR2(100),
  descriere VARCHAR2(600),
  FOREIGN KEY(id_brand) REFERENCES BRANDS(id_brand)
);
INSERT INTO BRANDS(id_brand,nume_brand,detalii) VALUES(1,'Gucci','At the end of the 19th century, Guccio Gucci worked at exclusive hotels in London and in Paris. Impressed with the luxurious luggage of the guests, Gucci returned to Florence, where he set up shop and produced and sold the type of fine leather goods that he saw during his time abroad. The offerings of the early Gucci store were simple and only included leather items such as luggage, accessories, handbags, and shoes.');
INSERT INTO BRANDS(id_brand,nume_brand,detalii) VALUES(2,'Calvin Klein','In 1968, Klein founded Calvin Klein Limited, a coat shop in the York Hotel in New York City, with $10,000. The first Calvin Klein collection was a line of "youthful, understated coats and dresses" featured at the New York City store, Bonwit Teller.');
INSERT INTO BRANDS(id_brand,nume_brand,detalii) VALUES(3,'Marc Jacobs','At age 15, Jacobs worked as a stockboy at Charivari, a now-defunct avant-garde clothing boutique in New York City. While still at Parsons, Jacobs designed and sold his first line of hand-knit sweaters. He also designed his first collection for Reuben Thomas, Inc., under the Sketchbook label. With Robert Duffy, Jacobss creative collaborator, and business partner since the mid-1980s, he formed Jacobs Duffy Designs Inc.');
INSERT INTO BRANDS(id_brand,nume_brand,detalii) VALUES(4,'Yves Saint Laurent','In 1953, Saint Laurent submitted three sketches to a contest for young fashion designers, organized by the International Wool Secretariat. He won first place and was invited to attend the awards ceremony in Paris, in December of that year.[citation needed] While he and his mother were in Paris, they met Michel de Brunhoff, editor-in-chief of the French edition of Vogue magazine.');
INSERT INTO BRANDS(id_brand,nume_brand,detalii) VALUES(5,'DSQUARED2','Dean and Dan Caten were born in 1964 as Dean and Dan Catenacci in Toronto, Ontario and grew up in the Willowdale area. They are the youngest of nine children. Their father is from a small town near Sora, Italy.');
INSERT INTO BRANDS(id_brand,nume_brand,detalii) VALUES(6,'Giorgio Armani','Giorgio Armani is an Italian fashion house founded by Giorgio Armani which designs, manufactures, distributes and retails haute couture, ready-to-wear, leather goods, shoes, watches, jewelry, accessories, eyewear, cosmetics and home interiors. The brand markets these products under several labels, from the most expensive to the most accessible.: Armani Prive, Giorgio Armani, Emporio Armani, Armani Collezioni, AJ | Armani Jeans, AX | Armani Exchange. ');
INSERT INTO BRANDS(id_brand,nume_brand,detalii) VALUES(7,'Cristian Dior','Christian Dior, commonly known as Dior, is a French luxury goods company controlled and chaired by businessman Bernard Arnault who also heads LVMH – the worlds largest luxury group');
INSERT INTO BRANDS(id_brand,nume_brand,detalii) VALUES(8,'Dolce','Dolce is an Italian luxury industry fashion house founded in 1985 in Legnano by Italian designers Domenico Dolce and Stefano Gabbana. The two met in Milan in 1980 and worked for the same fashion house');


--parfumuri romantic-femei
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere) 
VALUES(1,'Gucci Perfume',240,14,'women',1,50,'romantic','Eau De Parfum','day','spring','Poze/GucciPerfume.jpg','iris,thyme,musk,cumin,citruses','A fragrance for the modern gucci woman, gucci bamboo is powerful yet feminine; a blend of exotic florals with deep woody notes');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere) 
VALUES(2,'Euphoria Perfume',120,9,'women',2,100,'romantic','Eau De Parfum','day','winter','Poze/EuphoriaPerfume.jpg','pomegranate,black violet,black orchid,mahogany,lotus,persimmon','Exotic floral-fruity fragrance Euphoria was launched in 2005. The fragrance is luminous and luscious like fruits notes of which are captured in it. Euphoria is mysterious and appealing like dark exotic flowers. It invites you to enjoy in joys of life.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere) 
VALUES(3,'Secret Obsession Perfume',15,20,'women',3,100,'romantic','Eau De Parfum','night','summer','Poze/SecretObsessionPerfume.jpg','Damascue rose,Egyptian jasmine, French orange Blossom,exotic plum,nutmeg spice','Secret Obsession by Calvin Klein is oriental floral fragrance for women. The noses behind this fragrance are Givaudan and Ann Gottlieb. Top notes are exotic plum, nutmeg (mace) and rose de damasc; middle notes are Egyptian jasmine, French orange blossom and seductive tuberose; base notes are cashmere woods, Madagascar vanilla, burnt amber and Australian sandalwood.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(4,'Lola Perfume',200, 17,'women','4',50,'romantic','Eau De Parfum','day','spring','Poze/LolaPerfume.jpg','pink peppercorns, ruby red grapefruit,fresh roses','Lola arrived on the market in August 2009. It was created in cooperation with Calice Becker, Yann Vasnier and consultations with Ann Gottlieb. Lola includes pink pepper, pear, ruby red grapefruit, peony, rose, geranium, vanilla, creamy musk and tonka. Face of this perfume is Karlie Kloss');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(44,'Lady Million',230, 12,'women',4,100,'romantic','Eau De Parfum','day','autumn','Poze/LadyMillion.jpg','pink peppercorns, ruby red grapefruit,fresh roses','1 Million is one of the most popular fragrances launched in last several years. After the edition for men, women version inspired by gold and wealth was expected. Two years after men`s edition, fragrant lady finally appears - Lady Million!');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(45,'Cinema',210, 12,'women',4,50,'romantic','Eau De Parfum','day','autumn','Poze/Cinema.jpg','pink peppercorns, ruby red grapefruit,fresh roses','Cinema can make every woman feel like a star. It is a fragrance for glamorous women who live under the spotlights, self-confident and elegant, women who know how to draw the attention. A seductive flavor reminds of Hollywood beauties from the romantic love movies, glamourous evening gowns, Hollywood hairstyles, high heels, black seamed stocking.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(46,'Chanel N°5',400, 11,'women',8,100,'romantic','Eau De Parfum','day','winter','Poze/Channel.jpg','pink peppercorns, ruby red grapefruit,fresh roses','Created by Gabrielle Chanel to be the ultimate in femininity, N°5 has cast a spell on millions of women — and men — around the world. Inimitably luxurious and infinitely seductive, its legend lives, each year adding to its mystery, its depth, its desirability.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(47,'Anucci',130, 10,'women',7,50,'romantic','Eau De Parfum','day','summer','Poze/Anucci.jpg','pink peppercorns, ruby red grapefruit,fresh roses','Anucci Femme is a floral oriental fragrance with notes of iris, jasmine and peru balsam. Available as 100 ml EDT. Anucci Femme was launched during the 1990`s.');

--parfumuri romantice-barbati
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(5,'La Nuit De Lahomme',200,15,'men',4,100,'romantic','Cologne','day','summer','Poze/LaNuitPerfume.jpg','cardamom,lavender,bergamot,citrus','Yves Saint Laurent La Nuit de l`Homme is a new masculine representative of the house of YSL and it will appear on the market in March 2009. The perfume is announced as one full of contrasts and tensions.
A veil of mystery and an explosive spicy accord reveal cardamom with sparkling freshness of bergamot, lavender and cedar, which stand for strength of men. Cumin and vetiver in a base ensure a sensual finish and an opulent, elegant closure.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(6,'He Wood Cologne',15,29,'men',5,100,'romantic','Eau De Parfum','day','spring','Poze/HeWood.jpg','woody fragrance','He Wood is a Woody Aromatic fragrance for men. He Wood was launched in 2007. The nose behind this fragrance is Daphne Bugey. Top notes are violet and violet leaf; middle notes are vetiver and cedar; base notes are amber, musk and fir.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(7,'Gucci Cologne',50,5,'men',1,50,'romantic','Cologne','night','autumn','Poze/gucciCologne.jpg','bergamot,cypress,violet','Gucci Cologne by Gucci, A modern and masculine woody chypre for men and the companion to gucci perfume for women . This fragrance opens with notes of bergamot, cypress and violet the heart containing tobacco leaves and jasmine and the base notes consisting of patchouli, amber and elemi ');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(8,'Euphoria Intense',120,3,'men',2,100,'romantic','Cologne','night','winter','Poze/EuphoriaIntense.jpg','ginger,pepper,savory black basil,cedar','This fragrance is sweeter and more intensive, less aromatic but significantly more oriental. The notes are myrrh, spices, ambergris, vetiver, labdanum and agar wood. The bottle is similar to the shape of the previous edition of Euphoria, although it has a modern, more elegant design in the colors of amber.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(81,'Tom Ford',190,3,'men',5,50,'romantic','Eau De Parfum','night','spring','Poze/TomFord.jpg','Opoponax, amber, Indonesian patchouli, vetiver, civet, vanilla','After his latest Violet Blonde, Tom Ford offers a masculine counterpart; mysterious, spicy, full-bodied and at the same time elegant. "Enigmatic, complex and surprising," this is Ford`s most satisfying foray into perfume so far, as he reveals himself');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(82,'Dunhill',150,3,'men',7,50,'romantic','Eau De Parfum','night','winter','Poze/Dunhill.jpg','ginger,pepper,savory black basil,cedar','Dunhill for Men by Alfred Dunhill is a Woody Spicy fragrance for men. Dunhill for Men was launched in 1934. Top notes are lavender, geranium, nutmeg and amalfi ');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(83,'Bvlgari',200,3,'men',8,50,'romantic','Cologne','night','summer','Poze/Bvlgari.jpg','ginger,pepper,savory black basil,cedar','Bvlgari Pour Homme by Bvlgari is a Woody Floral Musk fragrance for men. Bvlgari Pour Homme was launched in 1996. The nose behind this fragrance is Jacques Cavallier.');

--parfumuri casual-femei
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(91,'Emporio Armani Perfume',120,3,'women',6,100,'casual','Eau de Perfume','day','summer','Poze/EmporioArmani.jpg','vanilla,sandalwood,heliotrope','The sensory blend is a surprising gourmand fragrance to give a stone a flavour and to a woman a self confident and audacious feeling.The rose, a symbol of femininity is made edible and succulent through the addition of a touch of litchi and raspberry.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(10,'Daisy Perfume',220,10,'women',3,100,'casual','Eau de Perfume','night','spring','Poze/DaisyPerfume.jpg','strowberry,pink grapefruit','Enter the world of Daisy: fresh and feminine, with a playful innocence. The heart of Daisy is floral with vintage edge of violet. Sophisticated, with a touch of whimsy, violet captures the eclectic, timeless flavor of Marc Jacobs` groundbreaking feminine designs.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(11,'She Wood Perfume',300,6,'women',5,50,'casual','Eau de Perfume','day','winter','Poze/SheWood.jpg','citrus,lemon,neroli','She Wood was created in cooperation with perfumer Daphne Bugey, and is composed of three accords: light, intensive and woody ones.
The creation was started from the base of the perfume for men and was shaped by adding notes and aromas of a fragrance for women. This is not a classic girly perfume, but can be categorized as a unisex. The fragrance aims at women who like using perfumes for men.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(12,'Dolce Vita Perfume',450,2,'women',7,100,'casual','Eau de Perfume','night','summer','Poze/DolceVita.jpg','magnolia,lily,peach','This is a sweet oriental fragrance with a spicy woody base. This perfume of joy and happiness reminds us of hot and sunny summer days-the scent of easy living. Top notes include lily, magnolia and rose followed by peach, apricot and cinnamon in its heart while the drydown notes are sandal, heliotrope and vanilla.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(13,'Bvlgari Green Tea',100,2,'women',3,50,'casual','Eau de Perfume','night','spring','Poze/BvlgariTea.jpg','magnolia,lily,peach','Bvlgari`s signature Green Tea perfume is the perfect summertime scent, even though it still smells wonderful any time of year. The delicate fragrance is light and relaxing, with the citrusy aroma of green tea coming through to subtly enliven the long-lasting scent.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(14,'Marc Jacobs Daisy',300,2,'women',2,100,'casual','Eau de Perfume','night','summer','Poze/MJ.jpg','strawberry,ruby red grapefruit mixing with gardenia,musk,vanilla','Like the fun, daisy-designed bottle, Marc Jacobs` Daisy perfume is lively, youthful and full of charm. The scent is super fruity.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(15,'Chloé',250,2,'women',7,50,'casual','Eau de Perfume','night','winter','Poze/Chloe.jpg','peony, freesia, lychee','Ah, Chloé. So simple. So sweet. So elegant yet understated. Just like the French fashion line, this eau de parfum is sophisticated and fresh, perfect for any woman seeking a chic and smooth scent.');


--parfumuri casual-barbati
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(16,'The One',68,10,'men',8,100,'casual','Cologne','day','autumn','Poze/TheOne.jpg','rosemary,lily,coriander,cardamom','The One for Men bottle symbolizes the contemporary luxury of Dolce. The proportions of the bottle recall a tailored suit made by the fashion house.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(17,'Emporio Armani Cologne',90,7,'men',6,50,'casual','Cologne','day','summer','Poze/EmporioArmani2.jpg','citrus,sage,elegant cardamom','Introduced in 1998. Fragrance notes: spices, vetiver and low undertones of aromatic woods and musk. Recommended use: casual.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(18,'Obsession',35,10,'men',2,100,'casual','Cologne','night','spring','Poze/Obsession.jpg','grapefruit,coriander,cardamom','Obsession for Men was launched in 1986, a year after the female version. This fragrance pair belongs to one of the most popular ones in the 80s. In 2005, their nighttime heir was presented: Obsession Night. Obsession for Men is the 1987 FiFi award winner.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(19,'Kouros Cologne',95,4,'men',2,100,'casual','Cologne','night','autumn','Poze/Kouros.jpg','artemisia,coriander,bergamot','Kouros by Yves Saint Laurent is a Aromatic Fougere fragrance for men. Kouros was launched in 1981. The nose behind this fragrance is Pierre Bourdon. Top notes are aldehydes, artemisia, coriander, clary sage and bergamot.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(20,'Bois du Portugal',180,4,'men',4,50,'casual','Eau De Parfum','night','summer','Poze/BoisPortugal.jpg','artemisia,coriander,bergamot','Powdery, earthy, and woody, Bois du Portugal by CREED was inspired by the fragrant trees of Portugal.  Take note of the word “millesime” on the bottle – the millesime designation is used to signify that the best crops from a particular year`s harvest were used to create that bottle of the cologne.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(55,'La Nuit De L`Homme',230,4,'men',5,100,'casual','Cologne','night','autumn','Poze/laNuit.jpg','artemisia,coriander,bergamot','It`s not just the striking hexagonal design that distinguishes this cologne.  Yves Saint Laurent`s La Nuit De L`Homme is an homage to the mysteries of the night.  It`s dark, sophisticated, and intensely seductive.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(56,'Viktor Rolf Antidote',95,6,'men',7,50,'casual','Cologne','night','summer','Poze/viktor.jpg','artemisia,coriander,bergamot','Kouros by Yves Saint Laurent is a Aromatic Fougere fragrance for men. Kouros was launched in 1981. The nose behind this fragrance is Pierre Bourdon. Top notes are aldehydes, artemisia, coriander, clary sage and bergamot.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(57,'Play Intense',100,4,'men',8,50,'casual','Cologne','night','winter','Poze/play.jpg','wood, mandarin orange, pink pepper, coffee wood accord','The first thing you notice about Givenchy`s Play Intense is the packaging, which is designed to look like an mp3 player. The second is its hip and modern take on men`s fragrance');


--parfumuri elegant-femei
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(21,'Gucci Guilty',130,5,'women',1,50,'elegant','Eau de Perfume','day','summer','Poze/GucciGuilty.jpg','lychee,mandarin orange,wihte peach,bergamot','Guilty is the new Gucci fragrance that will be available from September 2010. It is designed for the glamorous, daring, brave, and very sexy girls who like to party and enjoy themselves. The face of the advertising campaign is Evan Rachel Wood, singer and actress.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(22,'Firever and Ever Perfume',244,2,'women',7,100,'elegant','Eau de Perfume','day','spring','Poze/foreverEver.jpg','water jasmine,rose,ivy','Freesia and Jasmine petals blended with Bulgarian Rose make Forever and Ever Dior a tender and delicate fragrance. ');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(23,'Opium',120,5,'women',4,50,'elegant','Eau de Perfume','night','winter','Poze/Opium.jpg','rosemary,lily,mandarin orange','Opulence, decadence, overt sensuality--traits of the Oriental masterpiece designed by Yves Saint Laurent as an homage to the women obsessed with YSL Haute Couture and Rive Gauche Prêt-à-Porter.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(24,'Diorissimo',345,5,'women',7,100,'elegant','Eau de Perfume','night','autumn','Poze/Diorissimo.jpg','rosemary,lily,liliac','Diorissimo is fresh and clear, just like a dewy, spring morning in the woods. Top notes include lily-of-the- valley and ylang-ylang, the heart is composed of amaryllis and boronia, leaving a jasmine trail.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(25,'Miss Dior',150,5,'women',3,50,'elegant','Eau de Perfume','night','aspring','Poze/MissDior.jpg','rosemary,lily,liliac','Miss Dior was first launched in 1947, as part of Christian Dior`s presentation of his first couture collection. The scent became an immediate must-have for women around the world, and still holds its place as one of the most popular perfumes on the market. The elegant, luxurious packaging makes it a true classic, as well as the fragrance’s fresh, citrusy scent, which contains notes of Italian mandarin, Egyptian jasmine and Indonesian patchouli.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(26,'Balenciaga Paris',200,5,'women',8,100,'elegant','Eau de Perfume','night','autumn','Poze/Balenciaga.jpg','rosemary,lily,liliac','A fully fragranced perfume, Balenciaga Paris is the perfect pick if you really want to make a scent statement. It contains strong, sexy notes of mossy wood, violet leaf, pepper, cedarwood, patchouli and vetiver. Plus, the blown-glass bottle`s creative design is reminiscent of the fashion label`s inimitable style');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(27,'Givenchy Dahlia Noir',450,5,'women',3,50,'elegant','Eau de Perfume','night','winter','Poze/Givenchy.jpg','rosemary,lily,liliac','The black dahlia flower is the inspiration behind this mysterious, sexy and soft perfume.Sandalwood, vanilla and amber all come together to exude an incredibly feminine fragrance. Like Givenchy`s earlier perfumes, the bottle is sturdy and sharply structured, with the Givenchy Paris name boldly displayed in the front.The black dahlia flower is the inspiration behind this mysterious, sexy and soft perfume.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(28,'Donna Karan`s Cashmere Mist',250,5,'women',8,50,'elegant','Eau de Perfume','night','spring','Poze/DKMist.jpg','musk, Lily of the Valley, suede, bergamot, sandalwood, orris root','Classic and clean, Donna Karan`s Cashmere Mist is a wonderfully light fragrance that`s perfect for any time of year. It makes for a great signature scent, as it`s perfect for any season, day or night. It`s soft and sensual yet also subdued');

--parfumuri elegant-barbati
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(29,'Rive Gauche',110,3,'men',4,100,'elegant','Cologne','day','autumn','Poze/RiveGauche.jpg','lychee,wihte peach,bergamot','Rive Gauche is a gentle, floral fragrance. Magnolia, gardenia and honeysuckle and combined with a blend of woody florals, sandalwood and oakmoss.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(50,'Armani Code',45,12,'men',6,50,'elegant','Cologne','day','winter','Poze/ArmaniCode.jpg','lemon,bergamot','A seductive fragrance for men, Armani Code is a sexy blend of fresh lemon and bergamot softened with hints of orange tree blossom and warmed with soothing guaiac wood, and tonka bean.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(51,'Higher energy',90,8,'men',7,100,'elegant','Cologne','night','spring','Poze/HigherEnergy.jpg','melon,juniper,grapefruit','A young, urban fragrance created for the man who is always open to new perspectives and horizons, composed around a harmony of fresh, woody and spicy notes of grapefruit, pepper and vetiver. Luminous and vibrant.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(52,'Obsession Cologne',210,6,'men',2,100,'elegant','Cologne','night','summer','Poze/Obsession2.jpg','seaweed,driftwood,tarragon,juniper,grapefruit','Obsession Cologne by Calvin Klein, Launched by the design house of Calvin klein in 1986, obsession is classified as a refreshing, oriental, woody fragrance.this masculine scent possesses a blend of lavender, mandarin, clove, nutmeg and amber ');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(53,'Usher',150,6,'men',3,50,'elegant','Cologne','night','summer','Poze/usher.jpg','melon,juniper,grapefruit','Usher For Men by Usher Cologne. As sophisticated as the entertainer, Usher for Men is a scent that`s sure to command the attention of anyone you encounter. Created by Usher in 2008, this fragrance combines sweet, fruity notes with fresh sea water and bay leaves.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(58,'I Am King ',49,6,'men',2,100,'elegant','Cologne','night','spring','Poze/Imaking.jpg','melon,seaweed,driftwood,tarragon','I Am King by Sean John Cologne. A staple for summertime wear, I Am King is a daring mens scent by Sean John. Royal and confident, this fragrance boldly proclaims your arrival with the sharp notes of tangerine and orange.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(59,'X Rocawear Cologne',90,6,'men',8,50,'elegant','Cologne','night','autumn','Poze/rocaCologne.jpg','melon,seaweed,driftwood,tarragon','X Rocawear by Jay-Z Cologne. Splash on a bit of X Rocawear by Jay-Z to leave yourself feeling clean, refreshed and confident all day long. Created for men, this masculine fragrance is perfect if you are looking to make a great first impression on that special someone or when giving a presentation at the office.');


--parfumuri sport-femei
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(70,'The One Perfume',120,5,'women',8,100,'sport','Eau de Perfume','day','summer','Poze/TheOne2.jpg','lychee,mandarin orange,wihte peach,bergamot','Conceptualized by Domenico Dolce and Stefano Gabbana, The One, beaming in gold, was meant to be seen, celebrated and adored. The bottle pays homage to perfumery tradition while being a perfect example of  luxurious style.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(71,'Gucci Rush Perfume',78,8,'women',1,100,'sport','Eau de Perfume','day','spring','Poze/GucciRush.jpg','gardenia,rose,lily,freesia','Gucci Rush is a very attractive and recognizable fragrance, impulsive and irresistible, just like love at first sight. The name of the fragrance "Rush" reminds of stimulative drug, very widespread in America during 1980s.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(72,'Emporio Armani Diamonds',200,3,'women',5,50,'sport','Eau de Perfume','night','winter','Poze/EmporioArmaniDiamonds.jpg','litchi,raspberry,rose,amber,vetiver,vanilla','This perfume was created by Thierry Wasser of Firmenich and the fragrance is classified as gourmand-floral. The top notes are litchi and raspberry, the middle notes – freesia and lily of the valley, and the base are vetiver, cedar wood, patchouli and vanilla.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(73,'Acqua Di Gio Perfume',190,5,'women',6,100,'sport','Eau de Perfume','night','autumn','Poze/AcquaDiGio.jpg','peony,violet,musk vodka,peach,pineapples','Acqua di Gioia is a hymn to nature in all its forms. It is a clean, incredibly fresh, aquatic scent that is ultra-approachable, yet memorable');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(74,'Burberry Sport',120,5,'women',7,100,'sport','Eau de Perfume','day','summer','Poze/Burberry.jpg','lychee,seaweed,driftwood,tarragon','Conceptualized by Domenico Dolce and Stefano Gabbana, The One, beaming in gold, was meant to be seen, celebrated and adored. The bottle pays homage to perfumery tradition while being a perfect example of  luxurious style.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(75,'Blue Seduction',150,2,'women',1,50,'sport','Eau de Perfume','day','autumn','Poze/BSwoman.jpg','lychee,mandarin orange,white peach,bergamot','After the edition for men, Blue Seduction , the version for women appeared in 2008 at the market. This seductive perfume arrives in a transparent, azure bottle, having the same shape as the edition for men. It was designed to reach balance and reflection of water and light.');

--parfumuri sport-barbati
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(76,'Acqua Di Gio Cologne',190,2,'men',6,50,'sport','Cologne','day','winter','Poze/AcquaDiGio2.jpg','coriander,freesia,cyclamen','Inspired by beauty of Pantellerie, where he spent his vacation, Armani created the aroma of Aqua di Gio for men and women. The fragrance for men is a scent of freedom, full of wind and water.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(77,'Eternity Summer',140,7,'men',2,100,'sport','Cologne','day','summer','Poze/eternitysummer.jpg','seaweed,driftwood,tarragon','Calvin Klein continues with the tradition of limited edition summer fragrances. Eternity Summer and Eternity for Men Summer versions for 2014 evoke a peaceful, blissful and relaxing day at the beach.
Eternity for Men Summer begins with juniper berries, pear, basil and watermelon. Its aromatic - spicy heart includes cardamom, lavender and thyme, placed at the base of amber, sandalwood and musk');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(78,'Escape',99,2,'men',2,100,'sport','Cologne','night','autumn','Poze/Escape.jpg','melon,juniper,grapefruit,mango','Escape by Calvin Klein is an Aromatic Green fragrance for men. Escape was launched in 1993. The nose behind this fragrance is Steve Demercado. Top notes are eucalyptus, melon, juniper, grapefruit, mango and bergamot; middle notes are rosemary, cypress, fir, sage, birch and sea note');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(79,'Acqua Di Gio Cologne',190,2,'men',2,50,'sport','Eau De Parfum','day','winter','Poze/AcquaDiGio2.jpg','coriander,freesia,cyclamen','Inspired by beauty of Pantellerie, where he spent his vacation, Armani created the aroma of Aqua di Gio for men and women. The fragrance for men is a scent of freedom, full of wind and water.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(90,'Boss Bottled Sport',200,2,'men',5,100,'sport','Cologne','day','spring','Poze/BossSport.jpg','seaweed,driftwood,tarragon','Boss Bottled Sport, the sporty edition of the men`s fragrance Boss Bottled from 1998, was presented in spring 2012. The scent is described as fresh, energetic and very masculine, aiming at men of competitive spirit willing to challenge themselves.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(101,'Zara Sport Pour Homme',250,2,'men',7,50,'sport','Eau De Parfum','day','winter','Poze/zara.jpg','coriander,freesia,cyclamen','Zara Sport Pour Homme by Zara is a Woody Aromatic fragrance for men. Top notes are bergamot and melon; middle notes are apple and thyme; base note is sandalwood.');
INSERT INTO PARFUM(id_parfum,nume_parfum,pret,stoc,sex,id_brand,gramaj,categorie,concentratie,ocazie,anotimp,poza,ingrediente,descriere)
VALUES(100,'Sport for Men',100,2,'men',8,100,'sport','Cologne','day','summer','Poze/SportMan.jpg','seaweed,driftwood,tarragon','Explore two spirited expressions of masculinity. The ultimate fragrance for the consummate sportsman.');

