  
INSERT INTO DETALII_COMANDA(nr_comanda,id_parfum,cantitate) VALUES(7,1,5);
INSERT INTO DETALII_COMANDA(nr_comanda,id_parfum,cantitate) VALUES(8,2,6);
INSERT INTO DETALII_COMANDA(nr_comanda,id_parfum,cantitate) VALUES(9,3,12);
INSERT INTO DETALII_COMANDA(nr_comanda,id_parfum,cantitate) VALUES(4,4,2);
INSERT INTO DETALII_COMANDA(nr_comanda,id_parfum,cantitate) VALUES(2,5,5);
INSERT INTO DETALII_COMANDA(nr_comanda,id_parfum,cantitate) VALUES(1,6,5);
INSERT INTO DETALII_COMANDA(nr_comanda,id_parfum,cantitate) VALUES(10,7,4);
INSERT INTO DETALII_COMANDA(nr_comanda,id_parfum,cantitate) VALUES(11,11,5);
INSERT INTO DETALII_COMANDA(nr_comanda,id_parfum,cantitate) VALUES(12,12,9);
INSERT INTO DETALII_COMANDA(nr_comanda,id_parfum,cantitate) VALUES(13,55,5);
INSERT INTO DETALII_COMANDA(nr_comanda,id_parfum,cantitate) VALUES(14,56,10);
INSERT INTO DETALII_COMANDA(nr_comanda,id_parfum,cantitate) VALUES(15,21,5);
INSERT INTO DETALII_COMANDA(nr_comanda,id_parfum,cantitate) VALUES(16,22,6);
INSERT INTO DETALII_COMANDA(nr_comanda,id_parfum,cantitate) VALUES(17,23,7);
INSERT INTO DETALII_COMANDA(nr_comanda,id_parfum,cantitate) VALUES(18,24,10);
INSERT INTO DETALII_COMANDA(nr_comanda,id_parfum,cantitate) VALUES(19,25,3);
INSERT INTO DETALII_COMANDA(nr_comanda,id_parfum,cantitate) VALUES(20,26,2);
INSERT INTO DETALII_COMANDA(nr_comanda,id_parfum,cantitate) VALUES(21,27,1);