
DROP TABLE COMENTARII;

CREATE TABLE COMENTARII(
  id_user NUMBER,
  id_planta NUMBER,
  comentariu VARCHAR2(200),
  FOREIGN KEY(id_user) REFERENCES USERI(id_user),
  FOREIGN KEY(id_planta) REFERENCES PLANTE(id_planta)
);